### ISSUE TITLE
.NET Core/5.0 支持问题

### ISSUE THREAD

**Issue by LeaFrock** [aliyun/alibabacloud-csharp-sdk#1]
很高兴贵团队推出了新的升级版SDK，相较于之前原版，该版本提供了基于async/await的异步方法支持，值得肯定。

不过目前在实际应用中，我注意到该项目的核心组件Tea依赖于Nuget包[BouncyCastle](https://www.nuget.org/packages/BouncyCastle/)，而该Nuget包仅适用于.NET Framework程序。这导致了.NET 5项目中一旦引用该SDK的Nuget包，编译时IDE会发出警告：

`
已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8”而不是项目目标框架“net5.0”还原包“BouncyCastle 1.8.6.1”。此包可能与项目不完全兼容。
`

在RELEASE模式下Publish时会直接提示发布失败。

在[BouncyCastle官网](http://www.bouncycastle.org/csharp/)上可以看到发行记录，其中1.8.5版本发行记录中提到：

> 这是支持旧版.NET平台的最终功能版本。从1.9.0版开始，我们将针对更现代的.NET框架，并更新我们的构建和打包系统。1.8.x系列将继续收到错误修复，但新功能有限。

希望贵团队能及时关注该依赖项的更新，并尽快解决这个问题。最坏的可能是需要对NFX和Core后的.NET版本做分别依赖并打包，或者干脆换掉该依赖。

**Comment by guipie** [comment]
+1 
逼的我没办法，只能专门在开一个 python服务，发短信。
另外问一下：alibabacloud-csharp-sdk/dysmsapi-20170525/core/   是否支持.net5

**Comment by LeaFrock** [comment]
@guipie 面向.Net Standard 2.x意味着将得到.NET 5以后所有版本的支持。

**Comment by AxiosCros** [comment]
感谢反馈～已在新版本中弃用了 BouncyCastle 库，请使用以下命令将依赖包更新至最新版本。

```bash
dotnet add package Tea --version 1.0.11
dotnet add package AlibabaCloud.OpenApiUtil --version 1.0.8
```

**Comment by LeaFrock** [comment]
@AxiosCros 已更新，谢谢！
