### ISSUE TITLE
AlibabaCloud.SDK.Oss20190517 仍然无法使用

### ISSUE THREAD

**Issue by jacksonwj** [aliyun/alibabacloud-csharp-sdk#10]
根据 #7 的说法，该问题已经修复了，但是，又有新的问题了。

调用方法如下：

``` C#
using Oss = AlibabaCloud.SDK.Oss20190517;

var ossCfg = new Config
{
    AccessKeyId = <Key>,
    AccessKeySecret = <Secret>,
    Endpoint = "oss-cn-hangzhou.aliyuncs.com"
};

var cli = new Oss.Client(ossCfg);

var req = new Oss.Models.ListBucketsRequest
{
    MaxKeys = 500
};

try
{
    // var result = await cli.ListBucketsAsync(req);
    var result = await cli.ListBucketsWithOptionsAsync(req, new Dictionary<string, string>(), new RuntimeOptions());
    if (result == null || result.Body == null || result.Body.Buckets == null ||
        result.Body.Buckets.Buckets == null || result.Body.Buckets.Buckets.Count == 0)
    {
        return new(code: 400, msg: "暂无 Bucket");
    }

    return new(result.Body.Buckets.Buckets, result.Body.Buckets.Buckets.Count);
}
catch (TeaException e)
{
    return new(code: 500, msg: Common.AssertAsString(e.Message));
}
catch (Exception e)
{
    var ex = new TeaException(new Dictionary<string, string>
    {
        { "message", e.Message }
    });

    return new(code: 500, msg: Common.AssertAsString(ex.Message));
}
```

抛出异常如图所示：

![](https://user-images.githubusercontent.com/61455/183330343-643e164c-c37c-4d95-95c2-bea13b5671f3.png)

![](https://user-images.githubusercontent.com/61455/183330380-e53bf3df-c06a-48f3-bcb5-110c7271e293.png)

另外，不知道阿里云对于 .NET Core 的 SDK，有没有暂停的计划，如果要暂停了，麻烦告知一下，不然，对于官方 SDK，出现这样的 BUG，感觉有点匪夷所思。

**Comment by yndu13** [comment]
没有暂停计划，遇到问题反馈给我们，我们会持续修复并更新

**Comment by yndu13** [comment]
请将依赖的SDK信息发一下呢，包括AlibabaCloud.TeaXML、AlibabaCloud.GatewayOss、AlibabaCloud.SDK.Oss20190517的版本

**Comment by jacksonwj** [comment]
> 请将依赖的SDK信息发一下呢，包括AlibabaCloud.TeaXML、AlibabaCloud.GatewayOss、AlibabaCloud.SDK.Oss20190517的版本

是这个吗？

![](https://user-images.githubusercontent.com/61455/183372642-3cf7c7e7-72fb-4dc8-b150-6814e4100ccb.png)

BTW. 我的本地环境是

![](https://user-images.githubusercontent.com/61455/183372988-63626159-8909-4843-9005-5b1b5bf015c5.png)

**Comment by yndu13** [comment]
已排查到问题，是该接口的返回值的元数据定义有问题，与实际值不匹配，我们会尽快发布更新

**Comment by yndu13** [comment]
SDK已更新，AlibabaCloud.SDK.Oss20190517 --version 1.0.6
