### ISSUE TITLE
关于调用 API BatchAddDeviceGroupRelations 出错的问题

### ISSUE THREAD

**Issue by dblleaf** [aliyun/alibabacloud-csharp-sdk#6]
用在线调试的”发起调用“是不会有问题的，但是在本地测试或者线上测试就会报错
![image](https://user-images.githubusercontent.com/15872501/165246132-04e192b8-1275-48cd-8f28-b7e0f1d15ee5.png)

![image](https://user-images.githubusercontent.com/15872501/165245591-2b26e544-9baa-4988-809d-c35a978e8485.png)
已经确定该设备存在，且分组中没有存在该设备
AlibabaCloud.SDK.Iot20180120 v3.0.3

**Comment by dblleaf** [comment]
经过查看```AlibabaCloud.OpenApiUtil```和```AlibabaCloud.OpenApiClient```的代码发现，生成的```OpenApiRequest```的```Query```有误，其中
```csharp
"Device.1" = "AlibabaCloud.SDK.Iot20180120.Models.BatchAddDeviceGroupRelationsRequest+BatchAddDeviceGroupRelationsRequestDevice";
```
应该为
```csharp
"Device.1.ProductKey" = "ProductKey";
"Device.1.DeviceName" = "DeviceName";
```

**Comment by TsinghuaDream** [comment]
最新版本已修复。

**Comment by TsinghuaDream** [comment]
最新版本已修复。
