### ISSUE TITLE
OSS SDK调用`GetObjectMetaAsync`异常

### ISSUE THREAD

**Issue by LeaFrock** [aliyun/alibabacloud-csharp-sdk#9]
传入相同的bucket和key，**若key存在**——
`HeadObjectAsync`请求成功；
`GetObjectMetaAsync`抛出xml异常：
```
System.Xml.XmlException: Root element is missing.
   at AlibabaCloud.OpenApiClient.Client.ExecuteAsync(Params params_, OpenApiRequest request, RuntimeOptions runtime)
   at AlibabaCloud.SDK.Oss20190517.Client.GetObjectMetaWithOptionsAsync(String bucket, String key, GetObjectMetaRequest request, Dictionary`2 headers, RuntimeOptions runtime)
   at AlibabaCloud.SDK.Oss20190517.Client.GetObjectMetaAsync(String bucket, String key, GetObjectMetaRequest request)
```
**若key不存在**，则均抛出上述异常。

看文档这两个API含义相似，只是后者似乎返回的内容更少。

我的原始需求是想确认bucket里是否存在指定路径和名称的文件，新SDK里似乎没有提供直接的API。

**Comment by yndu13** [comment]
我们已经排查到问题，是因为SDK对返回异常的处理不正确。您先查看是否拥有oss:GetObject权限，参考文档：https://help.aliyun.com/document_detail/31985.html。我们这边则会尽快修复报错异常的正确抛出。

**Comment by LeaFrock** [comment]
> 您先查看是否拥有oss:GetObject权限

谢谢！权限是有的，否则HeadObjectAsync也不可能调用成功。

> 我的原始需求是想确认bucket里是否存在指定路径和名称的文件，新SDK里似乎没有提供直接的API。

自问自答一下，供其他人参考。原来老的OSS SDK提供了`DoesObjectExist`API，看了一下源码应该就是包装了Head接口：

```csharp
        public bool DoesObjectExist(string bucketName, string key)
        {
            try
            {
                using (HeadObjectCommand.Create(_serviceClient, _endpoint, CreateContext(Aliyun.OSS.Common.Communication.HttpMethod.Head, bucketName, key), bucketName, key).Execute())
                {
                }
            }
            catch (OssException ex)
           {
           //...
           }
          // ...
```

**Comment by yndu13** [comment]
了解，老的 OSS SDK 是对象存储团队手动维护的代码，对部分接口是做了额外的封装。而本库是自动生成的代码，目前还没有手动封装的部分，对象存储团队负责人已经提出未来一段时间会逐渐支持额外封装，提高 SDK 的使用体验。

**Comment by LeaFrock** [comment]
理解，上层的API接口使用代码生成是很好的想法。

不过依赖项目里的共用代码应该不是自动生成的代码？比如[这里](https://github.com/aliyun/darabonba-openapi/blob/master/csharp/core/Client.cs#L2124)：
* 直接`throw ex`导致异常堆栈到这里就截断了，增加了使用者排查异常根源的难度。
* try-catch的块太大，既影响性能，也影响问题定位

建议改为`throw;`，并且将try-catch块缩小到仅包含http请求这种异常不可控的逻辑上。
```txt
throw : If we use "throw" statement, it preserve original error stack information. In exception handling "throw" with empty parameter is also called re-throwing the last exception.

throw ex : If we use "throw ex" statement, stack trace of exception will be replaced with a stack trace starting at the re-throw point. It is used to intentionally hide stack trace information.
```

还有Tea、TeaXml项目里CSharp的共用实现部分，代码比较粗糙，希望贵团队有空能好好优化一下。

**Comment by yndu13** [comment]
嗯嗯好，throw ex这个库也是自动生成的，TeaXml和Tea倒是手动维护的，生成逻辑我们这边看看是否可优化这个问题。您那边有什么其他优化建议也可随时提出来。

**Comment by yndu13** [comment]
SDK已更新，AlibabaCloud.SDK.Oss20190517 --version 1.0.6，有什么问题辛苦随时反馈

**Comment by LeaFrock** [comment]
谢谢，该问题已修复。
